//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dprofiler.rc
//
#define IDC_MYICON                      2
#define IDD_FORMVIEW_MM_LEAK            101
#define IDD_DPROFILER_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_COPYRIGHT                   104
#define IDM_EXIT                        105
#define IDD_OPTION_SYMBOL_GENERAL       105
#define IDS_SAMPLE_LEFT                 105
#define IDS_SAMPLE_RIGHT                106
#define IDI_DPROFILER                   107
#define IDS_SAMPLE_UP                   107
#define IDI_SMALL                       108
#define IDS_SAMPLE_DOWN                 108
#define IDC_DPROFILE                    109
#define IDS_FLAME                       109
#define IDS_SAMPLE_REPORT               109
#define IDS_FULLSTACK                   110
#define IDS_SAMPLE_FULLSTACK            110
#define IDR_MAINFRAME                   128
#define IDI_ICON_GENERIC                129
#define IDI_ICON_FILTER_EDIT            130
#define IDI_ICON_FILTER_EXECUTE         131
#define IDI_ICON_FILTER_EXPORT          132
#define IDI_ICON_FILTER_IMPORT          133
#define IDD_DIALOG_CPU_ATTACH           134
#define IDD_DIALOG_CTRL                 135
#define IDD_PROPPAGE_MM                 139
#define IDD_PROPPAGE_IO                 140
#define IDD_PROPPAGE_CPU                141
#define IDD_PROPPAGE_ATTACH             142
#define IDD_PROPPAGE_RUN                143
#define IDD_DIALOG_APPLY                144
#define IDD_DIALOG_ANALYZE              145
#define IDI_ICON_APSARA                 147
#define IDB_BITMAP_WIZARD               148
#define IDD_FORMVIEW_IO                 150
#define IDD_FORMVIEW_CPU_HISTORY        152
#define IDD_FORMVIEW_CPU_SUMMARY        153
#define IDD_FORMVIEW_CPU_PC             154
#define IDD_FORMVIEW_CPU_FUNCTION       155
#define IDD_FORMVIEW_CPU_MODULE         156
#define IDD_FORMVIEW_MM_HEAP            157
#define IDD_FORMVIEW_MM_MODULE          158
#define IDD_FORMVIEW_BLANK              159
#define IDD_DIALOG_OPTION               160
#define IDD_FORMVIEW_CPU_STACK          161
#define IDD_OPTION_SOURCE_GENERAL       162
#define IDI_ICON_ADD                    162
#define IDI_ICON_REMOVE                 163
#define IDD_OLE_PROPPAGE_LARGE          163
#define IDD_OPTION_VIEW                 163
#define IDD_FORMVIEW_CPU_THREAD         164
#define IDD_FORMVIEW_CTLPANE            165
#define IDD_FORMVIEW_CTL                165
#define IDD_OPTION_GENERAL              166
#define IDD_FORMVIEW                    167
#define IDD_FORMVIEW_CPU_TREE           167
#define IDD_FORMVIEW1                   168
#define IDD_FORMVIEW_MM_TREE            168
#define IDD_FORMVIEW2                   169
#define IDD_FORMVIEW_CPU_FLAME          169
#define IDR_AVI3                        170
#define IDI_ICON_BACKWARD               171
#define IDI_ICON_DEDUCTION              172
#define IDI_ICON3                       173
#define IDI_ICON_FORWARD                173
#define IDI_ICON_SEARCH                 174
#define IDD_DIALOG_DEDUCTION            175
#define IDD_DIALOG_SOURCE               176
#define IDR_MENU_SOURCE                 177
#define IDD_DIALOG_HELP                 178
#define IDR_HELP                        179
#define IDD_FORMVIEW_MM_SUMMARY         180
#define IDD_FORMVIEW_MM_FLAME           181
#define IDB_BITMAP_ZOOMIN               182
#define IDB_BITMAP_ZOOMOUT              184
#define IDS_PRODUCT                     185
#define IDS_VERSION                     186
#define IDR_ACCELERATOR                 187
#define IDD_DIALOG_FULLSTACK            187
#define IDD_DIALOG_FLAME_REPORT         188
#define IDI_ICON_SAMPLELEFT             190
#define IDI_ICON_SAMPLERIGHT            191
#define IDI_ICON_SAMPLEDOWN             192
#define IDI_ICON_SAMPLEUP               193
#define IDI_ICON_SAMPLEBOTTOM           194
#define IDI_ICON_SAMPLETOP              195
#define IDI_ICON_SAMPLESTACK            196
#define IDI_ICON_SAMPLEREPORT           197
#define IDC_STATIC_BUILD                1000
#define IDC_LIST_VERSION                1002
#define IDC_LIST_TASK                   1004
#define IDC_LIST_DATA                   1004
#define IDC_LIST_PC                     1004
#define IDC_LIST_FUNCTION               1004
#define IDC_LIST_BACKTRACE              1004
#define IDC_COMBO_PERIOD                1015
#define IDC_BUTTON_REFRESH              1024
#define IDC_PROGRESS1                   1025
#define IDC_PROGRESS                    1025
#define IDC_EDIT_STACKDEPTH             1030
#define IDC_SPIN                        1031
#define IDC_CHECK_HEAP                  1032
#define IDC_BUTTON_PATH                 1033
#define IDC_BUTTON_START                1033
#define IDC_BUTTON_SYMBOL_ADD           1033
#define IDC_EDIT_IMAGEPATH              1034
#define IDC_BUTTON_SYMBOL_REMOVE        1034
#define IDC_EDIT_ARGUMENT               1035
#define IDC_EDIT_WORKPATH               1036
#define IDC_CHECK_VIRTUAL               1037
#define IDC_CHECK_HANDLE                1038
#define IDC_CHECK_GDI                   1039
#define IDC_CHECK_SOCKET                1042
#define IDC_CHECK_FILE                  1043
#define IDC_CHECK_DEVICE                1044
#define IDC_CHECK_INCLUDEWAIT           1045
#define IDC_RADIO_ATTACH                1046
#define IDC_RADIO_RUN                   1047
#define IDC_CHECK_PAUSE                 1051
#define IDC_LIST_INCLUSIVE              1053
#define IDC_LIST_EXCLUSIVE              1054
#define IDC_STATIC_INCLUSIVE            1055
#define IDC_STATIC_EXCLUSIVE            1056
#define IDC_LIST_ENV                    1057
#define IDC_LIST_CPU_SUMMARY            1057
#define IDC_STATIC_ENV                  1058
#define IDC_ZOOMIN                      1058
#define IDC_SPLIT                       1059
#define IDC_TREELIST                    1060
#define IDC_CHECK_HISTORY               1061
#define IDC_HOTKEY1                     1068
#define IDC_TREE_OPTION                 1069
#define IDC_LIST_SYMBOL                 1071
#define IDC_LIST_SOURCE                 1072
#define IDC_LIST_CPU_THREAD             1073
#define IDC_LIST_CPU_THREAD_THREAD      1074
#define IDC_LIST_CPU_HISTORY_THREAD     1075
#define IDC_BUTTON_SOURCE_ADD           1076
#define IDC_BUTTON_SOURCE_REMOVE        1077
#define IDC_CHECK_MS_SYMBOL_SERVER      1078
#define IDC_CUSTOM1                     1090
#define IDC_TREELIST_CPU_TREE           1090
#define IDC_TREELIST_MM_TREE            1090
#define IDC_CPU_FLAME                   1090
#define IDC_CPU_HISTORY_REBAR           1090
#define IDC_TREE_FULLSTACK              1090
#define IDC_FLAME_REPORT                1090
#define IDC_BUTTON1                     1091
#define IDC_BUTTON_MARK                 1091
#define IDC_BUTTON_CPU_SUMMARY          1091
#define IDC_BUTTON_EXPAND               1091
#define IDC_BUTTON2                     1092
#define IDC_BUTTON_STOP                 1092
#define IDC_BUTTON_COLLAPSE             1092
#define IDC_ANIMATE                     1093
#define IDC_LIST_CPU_THREAD_PC          1095
#define IDC_EDIT1                       1095
#define IDC_EDIT_THRESHOLD              1095
#define IDC_CPU_HISTORY_HORIZON         1096
#define IDC_BUTTON_PAUSE_RESUME         1096
#define IDC_CPU_HISTORY_VERTICAL        1097
#define IDC_CHECK1                      1097
#define IDC_CHECK_AUTOANALYZE           1097
#define IDC_CHECK_TRIMMING              1097
#define IDC_LIST_CPU_HISTORY_STACK      1098
#define IDC_STATIC_COPYRIGHT            1098
#define IDC_CPU_HISTORY_GRAPH           1099
#define IDC_TAB_FILE                    1099
#define IDC_RICHEDIT                    1100
#define IDC_LIST_MM_SUMMARY             1101
#define IDC_BUTTON_MM_SUMMARY           1102
#define IDC_MM_FLAME                    1103
#define IDC_SLIDER_ZOOM                 1104
#define IDC_ZOOMOUT                     1105
#define IDC_STATIC_RUN_TEXT             1107
#define IDC_STATIC_RUN_COLOR            1108
#define IDC_STATIC_WAIT_COLOR           1109
#define IDC_STATIC_WAIT                 1110
#define IDC_STATIC_WAIT_TEXT            1110
#define IDC_STATIC_IO_COLOR             1111
#define IDC_STATIC_IO_TEXT              1112
#define IDC_STATIC_SUMMARY              1116
#define IDC_FULLSTACK_SUMMARY           1116
#define IDC_BUTTON3                     1117
#define IDC_BUTTON_EXPORT               1117
#define IDM_NEW                         32773
#define IDM_STOP                        32774
#define IDM_FILTER_EXECUTE              32775
#define IDM_FILTER_IMPORT               32776
#define IDM_FILTER_EXPORT               32777
#define IDM_FILTER_EDIT                 32778
#define IDM_CPU                         32784
#define IDM_MEMORY                      32785
#define IDM_IO                          32786
#define IDM_MM                          32787
#define IDM_OPEN                        32790
#define IDM_SAVE                        32791
#define IDM_ANALYZE                     32793
#define IDM_OPTION                      32795
#define IDM_DEDUCTION                   32796
#define IDM_FIND                        32797
#define IDM_FIND_BACKWARD               32798
#define IDM_FIND_FORWARD                32799
#define ID_SOURCE_CLOSE                 32800
#define ID_SOURCE_COPYPATH              32801
#define ID_SOURCE_OPENFOLDER            32802
#define ID_SOURCE_OPENFROMSHELL         32807
#define IDM_HELP                        32809
#define IDM_SAMPLE_FORWARD              32811
#define IDM_SAMPLE_BACKWARD             32812
#define IDM_SAMPLE_UPWARD               32813
#define IDM_SAMPLE_DOWNWARD             32814
#define IDM_SAMPLE_FULLSTACK            32815
#define IDM_SAMPLE_REPORT               32816
#define IDC_STATIC                      -1
#define IDC_STATIC_PRODUCT              -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
